In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)
!nvidia-smi

2.9.0+cu126
Thu Dec  4 18:03:51 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   62C    P0             28W /   70W |     362MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------

In [4]:
def info(t):
	print("\n--------------------------------")
	print(f'{t} shape={t.shape} dtype={t.dtype} device={t.device} ndim={t.ndim}')
	print(t)
	print(t.T)

	print(t.sum())
	print(t.sum(dim=0))
	print(t.sum(dim=1))

	print(t.mean())
	print(t.mean(dim=0))
	print(t.mean(dim=1))

In [5]:
a = torch.tensor(
	[
		[
			[1.0,2.0,3.0], 
			[4.0,5.0,6.0]
		]
	]
)
info(a)


--------------------------------
tensor([[[1., 2., 3.],
         [4., 5., 6.]]]) shape=torch.Size([1, 2, 3]) dtype=torch.float32 device=cpu ndim=3
tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
tensor([[[1.],
         [4.]],

        [[2.],
         [5.]],

        [[3.],
         [6.]]])
tensor(21.)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[5., 7., 9.]])
tensor(3.5000)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[2.5000, 3.5000, 4.5000]])


In [6]:

t = torch.tensor(
	[
		[1.0,2.0,3.0], 
		[4.0,5.0,6.0]
	]
)
info(t)


--------------------------------
tensor([[1., 2., 3.],
        [4., 5., 6.]]) shape=torch.Size([2, 3]) dtype=torch.float32 device=cpu ndim=2
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])
tensor(3.5000)
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])


In [7]:
one_to_ten = torch.arange(1, 11)
print(one_to_ten)

t = torch.tensor([1,2,3])
print(t * t)
print(t.matmul(t))
print(t @ t)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([1, 4, 9])
tensor(14)
tensor(14)
